@Restaurants.API_HostAddress = https://localhost:7046


GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{id:int}

###

@id=0
GET {{Restaurants.API_HostAddress}}/api/Restaurants/5

###
