@Restaurants.API_HostAddress = https://localhost:7046


GET {{Restaurants.API_HostAddress}}/api/restaurants

###

@id=0
GET {{Restaurants.API_HostAddress}}/api/Restaurants/2

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{

}

###
